{
 "title": "Infrastructure",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Provisioned Memory",
   "type": "stat",
   "description": "Total memory provisioned to the node by AWS.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "AWS Allocated Memory" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemFree_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "Total"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "Non-Reclaimable"
    },
    {
     "expr": "((node_memory_MemAvailable_bytes-node_memory_MemFree_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "Reclaimable"
    }
   ]
  },
  {
   "title": "Memory Usage By Category (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"})/node_memory_MemTotal_bytes",
     "legendFormat": "Docker Containers"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "stat",
   "description": "The `node_cpu_seconds_total` metric in Prometheus has several modes that represent different states of the CPU. Here's what each mode means:\n\n- `mode=\"user\"`: The time spent by the CPU executing user processes. User processes are those initiated by users or by the operating system on behalf of users.\n- `mode=\"system\"`: The time spent by the CPU executing system processes. System processes are those initiated by the operating system itself.\n- `mode=\"idle\"`: The time during which the CPU was not executing any processes.\n- `mode=\"iowait\"`: The time during which the CPU was idle because it was waiting for input/output operations to complete.\n- `mode=\"irq\"`: The time spent by the CPU servicing hardware interrupts. An interrupt is a signal sent to the CPU by a device to indicate that it needs attention.\n- `mode=\"softirq\"`: Similar to `irq`, but for software interrupts. Software interrupts are signals sent by the kernel to schedule certain tasks.\n- `mode=\"steal\"`: The time during which a virtual CPU waits for a real CPU while the hypervisor is servicing another virtual process. Only applicable for virtualized environments.\n- `mode=\"nice\"`: The time spent by the CPU executing user processes with positive nice value (low priority).\n\nThese modes are mutually exclusive, meaning the CPU is either in one mode or another at any given time.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Usage By Containers (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage By Containers (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Bytes Transmitted Per Containers (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Bytes Received Per Containers (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}