version: "3"
name: desi_engineer

services:
  cms:
    environment:
      - VIRTUAL_HOST=blog.desiengineer.dev
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=blog.desiengineer.dev
      - LETSENCRYPT_RESTART_CONTAINER=true
    container_name: cms
    build:
      context: ../../
      dockerfile: ./deployment/services/app/cms/Dockerfile
      args:
        ENV: prod
        TARGET_PLATFORM: linux/arm64
    volumes:
      # Always mount directories rather than files in docker-compose because otherwise changes to files on host won't reflect in the container
      # this has something to do with how different os/editors/etc. make changes to files: https://github.com/moby/moby/issues/15793#issuecomment-135411504
      - ../secrets/cms/:/root/deployment/secrets/cms/:ro
    networks:
      - private-1
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 0s
    labels:
      logging: "promtail"
      logging_jobname: "docker_compose_logs"
