version: "3"
name: desi_engineer

# References:
# https://github.com/evertramos/nginx-proxy-automation
# https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md

# You can inspect the subnet of default docker bridge by running: netstat -rn or docket network inspect network_name
# Create a docker network: docker network create network_name
# Remove a docker network: docker network rm network_name
# List networks: docker network list

services:
  ################################################# DYNAMIC NGINX PROXY + SSL CONFIGURATION #########################################################################################
  nginx:
    container_name: nginx
    image: desiengineer/nginx:latest
    build:
      context: ../../
      dockerfile: ./deployment/services/proxy/nginx/Dockerfile
      args:
        # Sets the uid and gid of the nginx user inside the container that runs the nginx workers
        NGINX_UID: 1000
        NGINX_GID: 1000
    volumes:
      - ./proxy/nginx/data/etc_nginx_conf.d:/etc/nginx/conf.d
      - ./proxy/nginx/data/etc_nginx_vhost.d:/etc/nginx/vhost.d
      - ./proxy/nginx/data/usr_share_nginx_html:/usr/share/nginx/html
      - ./proxy/nginx/data/etc_nginx_certs:/etc/nginx/certs:ro

      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx/proxy.conf:/etc/nginx/proxy.conf
    depends_on:
      - cms
    networks:
      - public-1
      - private-1
    ports:
      - "80:80"
      - "443:443"
    labels:
      logging: "promtail"
      logging_jobname: "docker_compose_logs"

  docker-gen:
    environment:
      # can cause issues in some setups, hence always hash the upstream name
      - SHA1_UPSTREAM_NAME=true
    container_name: docker-gen
    image: nginxproxy/docker-gen:latest
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/custom_nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - ./proxy/docker_gen/templates:/etc/docker-gen/templates:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx
    networks:
      - private-1
    labels:
      logging: "promtail"
      logging_jobname: "docker_compose_logs"

  acme-companion:
    environment:
      - DEFAULT_EMAIL=desiengineer.dev@gmail.com
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - NGINX_PROXY_CONTAINER=nginx
    container_name: acme-companion
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx
    volumes:
      - ./proxy/nginx/data/etc_nginx_certs:/etc/nginx/certs:rw
      - ./proxy/acme_companion/data/etc_acme.sh:/etc/acme.sh

      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - private-1
    depends_on:
      - nginx
      - docker-gen
    labels:
      logging: "promtail"
      logging_jobname: "docker_compose_logs"
