---
- name: Configure server
  hosts: servers
  gather_facts: true
  tasks:
    - name: Configure time synchronization settings
      become: true
      block:
        - name: Start chronyd service
          ansible.builtin.service:
            name: chronyd
            state: started
            enabled: true

    # To get system time run: timedatectl
    # To get hardware time run: sudo hwclock --show
    - name: Configure time settings
      become: true
      block:
        - name: Set local timezone
          community.general.timezone:
            name: Asia/Kolkata
            hwclock: UTC # hardware clock should always be in UTC
        - name: Reboot the machine for the changes to take effect
          ansible.builtin.reboot:

    - name: Setup docker
      become: true
      block:
        - name: Start docker service
          ansible.builtin.service:
            name: docker
            state: started
            enabled: true
        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

    - name: Setup git
      block:
        - name: Setup git ssh key and config
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "600"
            force: true
          loop:
            - src: "{{ secrets_path }}/github/key_ed25519"
              dest: ~/.ssh/github_key_ed25519
            - src: "{{ configs_path }}/ssh/config"
              dest: ~/.ssh/config
        - name: Set github configuration
          ansible.builtin.copy:
            src: "{{ configs_path }}/github/config"
            dest: ~/.gitconfig
            mode: "664"
            force: true

    - name: Setup crontab
      become: true
      block:
        - name: Ensure crontab log directory exists
          ansible.builtin.file:
            path: /var/log/crontab
            state: directory
            mode: u=rwx,g=rx,o=
            owner: "{{ ansible_user }}"
        - name: Start crontab service
          ansible.builtin.service:
            name: cron # crond in CentOS
            state: started
            enabled: true

    # simply clone the repo
    - name: Setup codebase
      block:
        - name: Clone latest codebase
          ansible.builtin.git:
            repo: git@github.com:StarryFire/desi_engineer.git
            dest: ~/desi_engineer
            version: main
            update: true

    - name: Copy secrets
      ansible.builtin.include_tasks: ./copy_secrets.yaml

    - name: Setup cronjobs
      block:
        - name: Setup deploy on reboot cronjob
          ansible.builtin.cron:
            name: Deploy latest code on every reboot
            special_time: reboot
            # ref: https://stackoverflow.com/questions/52200878/crontab-journalctl-extra-messages
            # sends cron logs to /var/log/crontab/reboot-cron.log and systemd journal
            job: >
              cd ~/desi_engineer
              && make run cmd="deploy -f" 2>&1
              | tee >(while read line; do echo "[$(date -Iseconds)] $line" >> /var/log/crontab/reboot-cron.log; done;) >(systemd-cat -t reboot-cron)

    - name: Set ~/.bashrc_custom
      ansible.builtin.copy:
        src: "{{ configs_path }}/ansible_push/.bashrc_custom"
        dest: ~/.bashrc_custom
        mode: u=rw,g=r,o=r
        force: true
    - name: Set ~/.bash_login_custom
      ansible.builtin.copy:
        src: "{{ configs_path }}/ansible_push/.bash_login_custom"
        dest: ~/.bash_login_custom
        mode: u=rw,g=r,o=r
        force: true

    - name: Append entry point for .bashrc_custom to .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "source ~/.bashrc_custom"
        insertafter: EOF

    - name: Append entry point for .bash_login_custom to .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: "source ~/.bash_login_custom"
        insertafter: EOF
