# TODO: Move these files to a hosted service so we can fetch this when the cronjob runs and not only when the server is setup or deploy is done explicitly
- name: Copy secrets
  block:
    - name: Copy latest cms secrets
      ansible.builtin.copy:
        src: "{{ secrets_path }}/cms/prod/secrets.yaml"
        dest: ~/desi_engineer/deployment/secrets/cms/
        mode: preserve
        force: true
    - name: Copy latest docker secrets
      ansible.builtin.copy:
        src: "{{ secrets_path }}/docker/prod/tailscale.txt"
        dest: ~/desi_engineer/deployment/secrets/docker/
        mode: preserve
        force: true
