# TODO: Move these files to a hosted service so we can fetch this when the cronjob runs and not only when the server is setup or deploy is done explicitly
# destination paths ending with a '/' will copy the src to the destination regardless of whether the destination exists or not
- name: Copy secrets
  block:
    - name: Copy latest blog secrets
      ansible.builtin.copy:
        src: "{{ secrets_path }}/blog/prod/secrets.yaml"
        dest: ~/desi_engineer/deployment/secrets/blog/
        mode: preserve
        force: true
    - name: Copy latest docker secrets
      ansible.builtin.copy:
        src: "{{ secrets_path }}/docker/prod/tailscale.txt"
        dest: ~/desi_engineer/deployment/secrets/docker/
        mode: preserve
        force: true
    - name: Copy latest lets-encrypt secrets
      ansible.builtin.copy:
        src: "{{ secrets_path }}/lets_encrypt/prod/cloudflare.ini"
        dest: ~/desi_engineer/deployment/secrets/lets_encrypt/
        mode: preserve
        force: true
