apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy  # can be either proxy (grafana calls loki directly) or direct (client browser calls loki directly), related to websockets / live log tailing
  url: http://loki:3100
  isDefault: true
  editable: false
  jsonData:
    maxLines: 1000

# Hit the following api from inside grafana container in order to test loki's live tailing/websockets
# make sure to comment auth.proxy whitelist in config.ini, to allow adding auth headers from all ip addresses, before running the following commands to test loki websockets
# curl 'http://127.0.0.1:3000/grafana/api/datasources/proxy/uid/P8E80F9AEF21F6940/loki/api/v1/tail?query=%7Bjob%3D%22docker_compose_logs%22%7D%20%7C%3D%20%60%60' \
# -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0' \
# -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Sec-WebSocket-Version: 13' \
# -H 'Origin: https://desi-engineer-1.tail76efa.ts.net' -H 'Sec-WebSocket-Extensions: permessage-deflate' -H 'Sec-WebSocket-Key: uy0ft3il7goUOnNkQe5Qug==' \
# -H 'Connection: keep-alive, Upgrade' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: websocket' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' \
# -H 'Cache-Control: no-cache' -H 'Upgrade: websocket' -H 'X-WebAuth-User: desiengineer.dev@gmail.com' -H 'X-WebAuth-Name: Kartik'

# curl 'http://127.0.0.1:3000/grafana/api/live/ws' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0' \
# -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Sec-WebSocket-Version: 13' -H 'Origin: https://desi-engineer-1.tail76efa.ts.net' \
# -H 'Sec-WebSocket-Extensions: permessage-deflate' -H 'Sec-WebSocket-Key: Ev68tv9/8KT71ABum19gLA==' \
# -H 'Connection: keep-alive, Upgrade' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: websocket' -H 'Sec-Fetch-Site: same-origin' \
# -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade: websocket' -H 'X-WebAuth-User: desiengineer.dev@gmail.com' -H 'X-WebAuth-Name: Kartik'

