apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy  # can be either proxy (grafana calls loki directly) or direct (client browser calls loki directly)
  url: http://loki:3100
  isDefault: true
  editable: false
  jsonData:
    maxLines: 1000
